# example_vocab.yaml

## Where the samples will be written
save_data: data/wmt17/zh-en
## Where the vocab(s) will be written
src_vocab: data/wmt17/zh-en.vocab.src
tgt_vocab: data/wmt17/zh-en.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
# cannot build test vocab!
data:
    corpus_1:
        path_src: data/wmt17/train.src
        path_tgt: data/wmt17/train.tgt
    valid:
        path_src: data/wmt17/valid.src
        path_tgt: data/wmt17/valid.tgt

n_sample: -1
